# Book settings
title: My Blog
author: Laplx (Hao Chen)
logo: 'logo.png'

html:
  favicon: favicon.ico
  google_analytics_id: G-PPZXJ9B1BG

latex:
  latex_documents:
    targetname: book.tex、

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
